apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app # لازم الاسم ده يطابق الـ labels اللي في الـ Pods بتاعتك
  ports:
    - protocol: TCP
      port: 80        # البورت اللي الخدمة بتسمع عليه
      targetPort: 8080 # البورت اللي الأبلكيشن بتاعك شغال عليه جوه الـ Container
  type: LoadBalancer     # عشان تقدر تدخل من الـ Browser بتاع الـ Linux Mint بتاعك